version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy

hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user