# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Create application.properties file
      run: |
        mkdir -p ./src/main/resources
        cat > ./src/main/resources/application.properties <<EOF
        spring.application.name=effi

        ## spring ai key
        spring.ai.openai.api-key=${{ secrets.OPENAI_API_KEY }}
        spring.ai.openai.chat.options.model=gpt-3.5-turbo

        ## mariadb
        spring.datasource.driver-Class-Name=org.mariadb.jdbc.Driver
        spring.datasource.url=jdbc:mariadb://${{ secrets.AWS_DB_URL }}
        spring.datasource.username=root
        spring.datasource.password=${{ secrets.AWS_DB_PASSWORD }}

        spring.jpa.hibernate.ddl-auto=update

        hibernate.dialect=org.hibernate.dialect.MariaDBDialect
        spring.jpa.properties.hibernate.format_sql=true
        spring.jpa.show-sql=true

        # ### dummy data auto-create mode
        # spring.sql.init.mode=always
        # spring.sql.init.data-locations=classpath:database/effi_data.sql
        # spring.jpa.defer-datasource-initialization=true

        #email security
        spring.security.user.password=1

        # SMTP 설정
        spring.mail.host=smtp.gmail.com
        spring.mail.port=587
        spring.mail.username=teseuteu593@gmail.com
        spring.mail.password=fhxdmxcegzblwjvz
        spring.mail.properties.mail.smtp.auth=true
        spring.mail.properties.mail.smtp.starttls.enable=true
        spring.mail.properties.mail.smtp.starttls.required=true
        spring.mail.properties.mail.smtp.connectiontimeout=5000
        spring.mail.properties.mail.smtp.timeout=5000
        spring.mail.properties.mail.smtp.writetimeout=5000
        spring.mail.properties.auth-code-expiration-millis=300000

        # Redis 설정
        spring.data.redis.host=redis
        spring.data.redis.port=6379
        EOF

    - name: Create jwt.yml file
      run: |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/jwt.yml
        echo "secret-key: ${{ secrets.JWT_KEY }}" > ./src/main/resources/jwt.yml
        echo "expiration-minutes: 30" >> ./src/main/resources/jwt.yml
        echo "refresh-expiration-hours: 24" >> ./src/main/resources/jwt.yml
        echo "issuer: effi" >> ./src/main/resources/jwt.yml

    - name: set gradlew permissions
      run: chmod +x gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test
      env:
        AWS_DB_URL: ${{ secrets.AWS_DB_URL }}
        AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: effi
        path: build/libs/

    # 배포
  deploy:
    needs : build
    runs-on: ubuntu-latest

    steps:
    - name: Get Github Actions IP
      id: ip
      uses: haythem/public-ip@v1.2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: #해당 단계 수행시 필요한 값들 지정
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: effi
        path: build/libs/

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > effi_BE_KEY.pem
        chmod 600 effi_BE_KEY.pem
        scp -i effi_BE_KEY.pem -o StrictHostKeyChecking=no build/libs/effi-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/effi-0.0.1-SNAPSHOT.jar
        ssh -i effi_BE_KEY.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_USERNAME }}/effi-0.0.1-SNAPSHOT.jar > app.log 2>&1 &"
        rm -f effi_BE_KEY.pem



    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    #   with:
    #     gradle-version: '8.5'
    #
    # - name: Build with Gradle 8.5
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
